services:
  # ---------------- API GATEWAY ----------------
  antifraud-api:
    build: .
    container_name: antifraud-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORKER_MODE: api
    ports:
      - "8000:8000"   
    depends_on:
      database:
        condition: service_healthy
    networks:
      - antifraud-network
# ---------------- REALTIME WORKER ----------------
  antifraud-realtime:
    build: .
    container_name: antifraud-realtime
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORKER_MODE: realtime
    expose:
      - "8000" 
    depends_on:
      database:
        condition: service_healthy
    networks:
      - antifraud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/internal/fraud/health"]
      interval: 30s
      timeout: 3s
      retries: 3
 # ---------------- BATCH WORKER ----------------
  antifraud-batch:
    build: .
    container_name: antifraud-batch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORKER_MODE: batch
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - antifraud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/internal/fraud/health"]
      interval: 30s
      timeout: 3s
      retries: 3
# ---------------- DATABASE ----------------
  database:
    image: postgres:16
    container_name: antifraud-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - antifraud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  antifraud-network:
    driver: bridge

volumes:
  postgres_data:
